// Mocks generated by Mockito 5.4.6 from annotations
// in murder_party/test/ui/home/widgets/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:collection' as _i2;
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:murder_party/domain/model/murder_party_session.dart' as _i4;
import 'package:murder_party/domain/model/result.dart' as _i6;
import 'package:murder_party/ui/home/view_models/home_view_model.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUnmodifiableListView_0<E> extends _i1.SmartFake
    implements _i2.UnmodifiableListView<E> {
  _FakeUnmodifiableListView_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeViewModel extends _i1.Mock implements _i3.HomeViewModel {
  @override
  _i2.UnmodifiableListView<_i4.MurderPartySession> get murderPartySessions =>
      (super.noSuchMethod(
            Invocation.getter(#murderPartySessions),
            returnValue: _FakeUnmodifiableListView_0<_i4.MurderPartySession>(
              this,
              Invocation.getter(#murderPartySessions),
            ),
            returnValueForMissingStub:
                _FakeUnmodifiableListView_0<_i4.MurderPartySession>(
                  this,
                  Invocation.getter(#murderPartySessions),
                ),
          )
          as _i2.UnmodifiableListView<_i4.MurderPartySession>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<_i6.Result<List<_i4.MurderPartySession>>> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue:
                _i5.Future<_i6.Result<List<_i4.MurderPartySession>>>.value(
                  _i7.dummyValue<_i6.Result<List<_i4.MurderPartySession>>>(
                    this,
                    Invocation.method(#load, []),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i6.Result<List<_i4.MurderPartySession>>>.value(
                  _i7.dummyValue<_i6.Result<List<_i4.MurderPartySession>>>(
                    this,
                    Invocation.method(#load, []),
                  ),
                ),
          )
          as _i5.Future<_i6.Result<List<_i4.MurderPartySession>>>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
